<?php
session_start();$open_connect=1;require('connect.php');
if(!isset($_SESSION['id_account']) || ($_SESSION['role_account']??'')!=='admin'){header('Location:form-login.php');exit;}
$errors=[];
function esc($v){global $connect;return mysqli_real_escape_string($connect,(string)$v);}
function images_list($v){return array_values(array_filter(array_map('trim',explode('|',(string)$v))));}
function delete_uploaded_images($value,$prefixes){foreach(images_list($value) as $img){$path=__DIR__.'/'.ltrim($img,'/');$ok=false;foreach($prefixes as $p){if(strpos($img,$p)===0){$ok=true;break;}}if($ok&&is_file($path))@unlink($path);}}
function upload_images($field,$dir,$prefix){$out=[];if(!isset($_FILES[$field])||!is_array($_FILES[$field]['name']))return $out;if(!is_dir(__DIR__.'/'.$dir))mkdir(__DIR__.'/'.$dir,0755,true);$f=$_FILES[$field];for($i=0;$i<count($f['name']);$i++){ $err=$f['error'][$i]??UPLOAD_ERR_NO_FILE;if($err===UPLOAD_ERR_NO_FILE)continue;if($err!==UPLOAD_ERR_OK)throw new Exception('อัปโหลดรูปไม่สำเร็จ');$ext=strtolower(pathinfo($f['name'][$i],PATHINFO_EXTENSION));if(!in_array($ext,['jpg','jpeg','png','webp'],true))throw new Exception('รองรับเฉพาะ JPG, PNG และ WEBP');$file=$dir.$prefix.uniqid().'.'.$ext;if(!move_uploaded_file($f['tmp_name'][$i],__DIR__.'/'.$file))throw new Exception('บันทึกไฟล์รูปไม่สำเร็จ');$out[]=$file;}return $out;}
$allowed=['ร้านอาหาร','คาเฟ่','ร้านค้า','อื่นๆ'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='delete'){ $id=(int)($_POST['id_shop']??0);$r=mysqli_query($connect,"SELECT image_shop FROM shop WHERE id_shop=$id LIMIT 1");$old=$r?mysqli_fetch_assoc($r):null;if($old&&mysqli_query($connect,"DELETE FROM shop WHERE id_shop=$id")){delete_uploaded_images($old['image_shop'],['images_shop/shop_','images_shop/admin-']);header('Location:admin-shops.php?deleted=1');exit;}$errors[]='ลบร้านไม่สำเร็จ';}
 if($action==='toggle'){ $id=(int)($_POST['id_shop']??0);mysqli_query($connect,"UPDATE shop SET status_shop=1-status_shop WHERE id_shop=$id");header('Location:admin-shops.php?updated=1');exit;}
 if($action==='save'){ $id=(int)($_POST['id_shop']??0);$name=trim($_POST['name_shop']??'');$cat=trim($_POST['category_shop']??'');$addr=trim($_POST['address_shop']??'');$desc=trim($_POST['description_shop']??'');$lat=$_POST['lat_shop']??'';$lng=$_POST['lng_shop']??'';
  if($name===''||!in_array($cat,$allowed,true)||!is_numeric($lat)||!is_numeric($lng))$errors[]='กรุณากรอกข้อมูลร้านและพิกัดให้ครบ';
  else try{
   $new=upload_images('image_shop','images_shop/','admin-');
   if($id){$r=mysqli_query($connect,"SELECT image_shop FROM shop WHERE id_shop=$id LIMIT 1");$old=$r?mysqli_fetch_assoc($r):null;$oldImages=images_list($old['image_shop']??'');$remove=array_map('strval',$_POST['remove_images']??[]);$keep=[];foreach($oldImages as $img){if(in_array($img,$remove,true))delete_uploaded_images($img,['images_shop/shop_','images_shop/admin-']);else $keep[]=$img;}$all=array_merge($keep,$new);$sql="UPDATE shop SET name_shop='".esc($name)."',category_shop='".esc($cat)."',address_shop='".esc($addr)."',description_shop='".esc($desc)."',lat_shop=".(float)$lat.",lng_shop=".(float)$lng.",image_shop='".esc(implode('|',$all))."' WHERE id_shop=$id";}
   else{$sql="INSERT INTO shop (id_account,name_shop,category_shop,address_shop,description_shop,lat_shop,lng_shop,image_shop,status_shop) VALUES (".(int)$_SESSION['id_account'].",'".esc($name)."','".esc($cat)."','".esc($addr)."','".esc($desc)."',".(float)$lat.",".(float)$lng.",'".esc(implode('|',$new))."',1)";}
   if(mysqli_query($connect,$sql)){header('Location:admin-shops.php?saved=1');exit;}$errors[]='บันทึกไม่สำเร็จ: '.mysqli_error($connect);
  }catch(Exception $e){$errors[]=$e->getMessage();}
 }
}
$editing=null;if(isset($_GET['edit'])){$id=(int)$_GET['edit'];$r=mysqli_query($connect,"SELECT * FROM shop WHERE id_shop=$id LIMIT 1");$editing=$r?mysqli_fetch_assoc($r):null;}
$q=trim($_GET['q']??'');$shops=[];$sql="SELECT s.*,a.username_account FROM shop s LEFT JOIN account a ON a.id_account=s.id_account";if($q!==''){$l='%'.esc($q).'%';$sql.=" WHERE s.name_shop LIKE '$l' OR s.category_shop LIKE '$l' OR s.address_shop LIKE '$l' OR s.description_shop LIKE '$l'";}$sql.=" ORDER BY s.id_shop DESC";$r=mysqli_query($connect,$sql);while($r&&($row=mysqli_fetch_assoc($r)))$shops[]=$row;
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>จัดการร้านอาหาร & คาเฟ่ | Admin</title>
<link rel="stylesheet" href="gallery.css"><link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;background:#faf9f5;color:#1d231d;font-family:Prompt,sans-serif}.wrap{width:min(1280px,calc(100% - 32px));margin:auto}.nav{background:#163a28;color:#fff}.nav .wrap{height:68px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:700}.navlinks{display:flex;gap:22px}.navlinks a{color:#dfe9e1;text-decoration:none;font-size:13px}.navlinks a.active{color:#fff;font-weight:600}.head{padding:34px 0 20px}.head h1{margin:0 0 5px;font-size:30px}.head p{margin:0;color:#68736c;font-size:13px}.notice{padding:11px 14px;border-radius:12px;margin-bottom:14px;background:#e8f3ec;color:#163a28}.err{background:#fdeceb;color:#8a2c25}.layout{display:grid;grid-template-columns:420px 1fr;gap:18px;padding-bottom:50px}.panel{background:#eef1e9;border-radius:22px;padding:20px}.panel h2{margin:0 0 15px;font-size:18px}.field{margin-bottom:12px}label{display:block;color:#68736c;font-size:12px;margin-bottom:5px}input,select,textarea{width:100%;border:1px solid #d8ded8;border-radius:11px;background:#fff;padding:10px;font:13px Prompt;color:#1d231d}textarea{min-height:75px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:9px}.btn{border:0;border-radius:999px;padding:9px 15px;font:600 12px Prompt;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.primary{background:#24593f;color:#fff}.ghost{background:#fff;color:#526058;border:1px solid #d8ded8}.danger{background:#fdeceb;color:#8a2c25}.muted{background:#eef1e9;color:#24593f}.search{display:flex;gap:8px;margin-bottom:12px}.search input{flex:1}.image-box{background:#fff;border:1px solid #d8ded8;border-radius:14px;padding:10px}.image-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.image-list{display:grid;gap:7px}.image-row{display:grid;grid-template-columns:1fr 32px;gap:6px}.existing{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:8px}.existing label{position:relative;margin:0}.existing img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px;display:block}.existing input{position:absolute;right:5px;top:5px;width:auto}.table{background:#fff;border-radius:18px;overflow:hidden}.item{display:grid;grid-template-columns:82px 1fr auto;gap:13px;padding:12px;border-bottom:1px solid #e3e6e1;align-items:center}.item:last-child{border-bottom:0}.thumb{width:82px;height:62px;border-radius:10px;background:#e5e9e3 center/cover no-repeat}.item h3{font-size:14px;margin:0 0 3px}.meta{font-size:11px;color:#68736c}.actions{display:flex;gap:6px;align-items:center}.status{font-size:11px;margin-top:3px}.show{color:#24593f}.hide{color:#9a3b34}.empty{padding:30px;text-align:center;color:#68736c}@media(max-width:900px){.layout{grid-template-columns:1fr}.item{grid-template-columns:65px 1fr}.item .actions{grid-column:2}.navlinks{gap:10px}}@media(max-width:600px){.navlinks{display:none}.row{grid-template-columns:1fr}}
</style></head><body>
<nav class="nav"><div class="wrap"><div class="logo">เที่ยวตาก · ADMIN</div><div class="navlinks"><a href="admin.php">แดชบอร์ด</a><a href="admin-places.php">สถานที่</a><a href="admin-shops.php" class="active">ร้านอาหาร & คาเฟ่</a><a href="admin-members.php">สมาชิก</a><a href="admin.php?logout=1">ออกจากระบบ</a></div></div></nav>
<div class="wrap"><div class="head"><h1>จัดการร้านอาหาร & คาเฟ่</h1><p>เพิ่ม แก้ไข ลบ ซ่อน/แสดง ค้นหา และจัดการรูปภาพหลายรูปของร้าน</p></div>
<?php if(isset($_GET['saved'])):?><div class="notice">บันทึกข้อมูลเรียบร้อยแล้ว</div><?php endif;?><?php if(isset($_GET['updated'])):?><div class="notice">อัปเดตสถานะเรียบร้อยแล้ว</div><?php endif;?><?php if(isset($_GET['deleted'])):?><div class="notice">ลบร้านเรียบร้อยแล้ว</div><?php endif;?><?php foreach($errors as $e):?><div class="notice err"><?php echo htmlspecialchars($e);?></div><?php endforeach;?>
<div class="layout"><section class="panel"><h2><?php echo $editing?'แก้ไขร้าน':'เพิ่มร้านใหม่';?></h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="save"><input type="hidden" name="id_shop" value="<?php echo (int)($editing['id_shop']??0);?>">
<div class="field"><label>ชื่อร้าน</label><input name="name_shop" value="<?php echo htmlspecialchars($editing['name_shop']??'');?>" required></div><div class="field"><label>หมวดหมู่</label><select name="category_shop" required><option value="">เลือกหมวดหมู่</option><?php foreach($allowed as $cat):?><option <?php echo (($editing['category_shop']??'')===$cat)?'selected':'';?> value="<?php echo htmlspecialchars($cat);?>"><?php echo htmlspecialchars($cat);?></option><?php endforeach;?></select></div>
<div class="field"><label>ที่อยู่ / จุดสังเกต</label><input name="address_shop" value="<?php echo htmlspecialchars($editing['address_shop']??'');?>"></div><div class="field"><label>รายละเอียด</label><textarea name="description_shop"><?php echo htmlspecialchars($editing['description_shop']??'');?></textarea></div>
<div class="row"><div class="field"><label>ละติจูด</label><input name="lat_shop" value="<?php echo htmlspecialchars($editing['lat_shop']??'');?>" required></div><div class="field"><label>ลองจิจูด</label><input name="lng_shop" value="<?php echo htmlspecialchars($editing['lng_shop']??'');?>" required></div></div>
<div class="image-box"><div class="image-head"><strong style="font-size:12px">รูปภาพ</strong><button type="button" class="btn primary" id="add-image">＋ เพิ่มรูป</button></div>
<?php if($editing&&images_list($editing['image_shop']??'')):?><div class="existing"><?php foreach(images_list($editing['image_shop']) as $img):?><label><img src="<?php echo htmlspecialchars($img);?>" alt=""><input type="checkbox" name="remove_images[]" value="<?php echo htmlspecialchars($img);?>"></label><?php endforeach;?></div><div style="font-size:10px;color:#68736c;margin-bottom:8px">ติ๊กที่รูปเพื่อลบตอนบันทึก</div><?php endif;?>
<div class="image-list" id="image-list"><div class="image-row"><input type="file" name="image_shop[]" accept="image/jpeg,image/png,image/webp"></div></div></div>
<div style="display:flex;gap:8px;margin-top:14px"><button class="btn primary">บันทึก</button><?php if($editing):?><a class="btn ghost" href="admin-shops.php">ยกเลิก</a><?php endif;?></div></form></section>
<section class="panel"><h2>ร้านทั้งหมด · <?php echo count($shops);?> รายการ</h2><form class="search" method="get"><input name="q" value="<?php echo htmlspecialchars($q);?>" placeholder="ค้นหาชื่อร้าน ที่อยู่ หมวดหมู่..."><button class="btn primary">ค้นหา</button></form><div class="table"><?php if(!$shops):?><div class="empty">ไม่พบร้าน</div><?php endif;?>
<?php foreach($shops as $s):$imgs=images_list($s['image_shop']);$img=$imgs[0]??'';$visible=(int)$s['status_shop']===1;?>
<div class="item"><div class="thumb gallery-card" style="background-image:url('<?php echo htmlspecialchars($img,ENT_QUOTES);?>')" data-gallery="<?php echo htmlspecialchars(json_encode($imgs,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),ENT_QUOTES);?>"></div><div><h3><?php echo htmlspecialchars($s['name_shop']);?></h3><div class="meta">📍 <?php echo htmlspecialchars($s['address_shop']?:'ไม่ระบุที่อยู่');?> · <?php echo htmlspecialchars($s['category_shop']);?></div><div class="meta">เพิ่มโดย <?php echo htmlspecialchars($s['username_account']??'ไม่ทราบชื่อ');?> · <?php echo count($imgs);?> รูป</div><div class="status <?php echo $visible?'show':'hide';?>"><?php echo $visible?'● กำลังแสดงผล':'● ถูกซ่อนอยู่';?></div></div><div class="actions"><a class="btn ghost" href="admin-shops.php?edit=<?php echo (int)$s['id_shop'];?>">แก้ไข</a><form method="post"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id_shop" value="<?php echo (int)$s['id_shop'];?>"><button class="btn muted"><?php echo $visible?'ซ่อน':'แสดง';?></button></form><form method="post" onsubmit="return confirm('ลบ <?php echo htmlspecialchars($s['name_shop'],ENT_QUOTES);?> ถาวรใช่ไหม?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="id_shop" value="<?php echo (int)$s['id_shop'];?>"><button class="btn danger">ลบ</button></form></div></div>
<?php endforeach;?></div></section></div></div>
<script src="gallery.js?v=20261007-admin-shop"></script><script>
const list=document.getElementById('image-list'),add=document.getElementById('add-image');add.onclick=()=>{const row=document.createElement('div');row.className='image-row';row.innerHTML='<input type="file" name="image_shop[]" accept="image/jpeg,image/png,image/webp"><button type="button" class="btn danger remove-image">×</button>';list.appendChild(row);row.querySelector('.remove-image').onclick=()=>row.remove();};
</script></body></html>