<?php
session_start();$open_connect=1;require('connect.php');
if(!isset($_SESSION['id_account'])||($_SESSION['role_account']??'')!=='admin'){header('Location:form-login.php');exit;}
if(isset($_GET['logout'])){session_destroy();header('Location:form-login.php');exit;}
$id=(int)$_SESSION['id_account'];$r=mysqli_query($connect,"SELECT * FROM account WHERE id_account=$id LIMIT 1");$me=$r?mysqli_fetch_assoc($r):[];
$count_places=(int)(mysqli_fetch_assoc(mysqli_query($connect,"SELECT COUNT(*) n FROM place"))['n']??0);
$count_shops=(int)(mysqli_fetch_assoc(mysqli_query($connect,"SELECT COUNT(*) n FROM shop"))['n']??0);
$count_visible=(int)(mysqli_fetch_assoc(mysqli_query($connect,"SELECT COUNT(*) n FROM shop WHERE status_shop=1"))['n']??0);
$count_accounts=(int)(mysqli_fetch_assoc(mysqli_query($connect,"SELECT COUNT(*) n FROM account"))['n']??0);
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | เที่ยวตาก</title><link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
*{box-sizing:border-box}body{margin:0;background:#faf9f5;color:#1d231d;font-family:Prompt,sans-serif}.wrap{width:min(1180px,calc(100% - 32px));margin:auto}.nav{background:#163a28;color:#fff}.nav .wrap{height:68px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:700}.who{display:flex;align-items:center;gap:10px;font-size:12px}.who img{width:34px;height:34px;border-radius:50%;object-fit:cover}.who a{color:#dfe9e1;text-decoration:none}.head{padding:42px 0 22px}.eyebrow{font-size:10px;letter-spacing:.18em;color:#7b867f;text-transform:uppercase}.head h1{font-size:32px;margin:8px 0 4px}.head p{margin:0;color:#68736c;font-size:13px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:22px}.stat{background:#fff;border:1px solid #e1e5df;border-radius:18px;padding:18px}.num{font-size:30px;font-weight:700;color:#163a28}.label{font-size:12px;color:#68736c;margin-top:3px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding-bottom:50px}.card{background:#eef1e9;border-radius:22px;padding:22px;text-decoration:none;min-height:170px;transition:.2s}.card:hover{transform:translateY(-3px);box-shadow:0 12px 30px rgba(20,40,30,.08)}.icon{font-size:28px}.card h2{font-size:18px;margin:10px 0 5px}.card p{font-size:12px;color:#68736c;line-height:1.7;margin:0}.go{display:inline-block;margin-top:14px;color:#24593f;font-size:12px;font-weight:600}@media(max-width:850px){.stats{grid-template-columns:1fr 1fr}.cards{grid-template-columns:1fr}}@media(max-width:560px){.who span{display:none}.stats{grid-template-columns:1fr}}
</style></head><body>
<nav class="nav"><div class="wrap"><div class="logo">เที่ยวตาก · ADMIN</div><div class="who"><?php if(!empty($me['images_account'])):?><img src="<?php echo htmlspecialchars('images_account/'.$me['images_account']);?>" alt=""><?php endif;?><span><?php echo htmlspecialchars($me['username_account']??'Admin');?> · admin</span><a href="admin.php?logout=1">ออกจากระบบ</a></div></div></nav>
<main class="wrap"><section class="head"><div class="eyebrow">TAK EXPLORE · ADMIN</div><h1>แดชบอร์ดจัดการเว็บไซต์</h1><p>จัดการสถานที่ ร้านอาหาร คาเฟ่ และสมาชิกจากหน้านี้</p></section>
<section class="stats"><div class="stat"><div class="num"><?php echo $count_places;?></div><div class="label">สถานที่เที่ยวทั้งหมด</div></div><div class="stat"><div class="num"><?php echo $count_shops;?></div><div class="label">ร้านทั้งหมด</div></div><div class="stat"><div class="num"><?php echo $count_visible;?></div><div class="label">ร้านที่กำลังแสดง</div></div><div class="stat"><div class="num"><?php echo $count_accounts;?></div><div class="label">สมาชิกทั้งหมด</div></div></section>
<section class="cards"><a class="card" href="admin-places.php"><div class="icon">🏞️</div><h2>จัดการสถานที่เที่ยว</h2><p>เพิ่ม แก้ไข ลบ ค้นหา และจัดการรูปหลายรูปของสถานที่ พร้อมเปิดดู Gallery</p><span class="go">เข้าสู่การจัดการ →</span></a>
<a class="card" href="admin-shops.php"><div class="icon">🍜</div><h2>จัดการร้านอาหาร & คาเฟ่</h2><p>เพิ่ม แก้ไข ลบ ซ่อน/แสดง ค้นหา และจัดการรูปหลายรูปของร้าน</p><span class="go">เข้าสู่การจัดการ →</span></a>
<a class="card" href="admin-members.php"><div class="icon">👥</div><h2>จัดการสมาชิก</h2><p>แก้ไขข้อมูลสมาชิก จัดการสิทธิ์ และปลดล็อกบัญชีที่ถูกล็อก</p><span class="go">เข้าสู่การจัดการ →</span></a></section></main></body></html>