<?php
session_start(); $open_connect=1; require('connect.php');
if(!isset($_SESSION['id_account'])){header('Location: form-login.php');exit;}
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เพิ่มข้อมูล | TAK EXPLORE</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="modern.css">
<style>
:root{--ink:#18231e;--muted:#68736c;--paper:#faf9f5;--cream:#f0eee5;--green:#183d31;--line:rgba(24,35,30,.13)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Prompt,sans-serif}a{text-decoration:none;color:inherit}
.container{width:min(1380px,calc(100% - 48px));margin:auto}
.nav{position:fixed;z-index:100;top:0;left:0;right:0;height:78px;background:rgba(250,249,245,.92);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}
.nav .container{height:78px;display:flex;align-items:center;gap:28px}
.logo{font:600 24px "Playfair Display",serif;color:var(--green);letter-spacing:.02em;white-space:nowrap}.logo span{font:500 10px Prompt,sans-serif;letter-spacing:.18em;color:var(--muted);margin-left:9px}
.links{display:flex;gap:28px;margin:auto;height:100%;align-items:center}.links a{font-size:13px;color:var(--muted);padding:28px 0;border-bottom:2px solid transparent;white-space:nowrap}.links a.active,.links a:hover{color:var(--green);border-bottom-color:#73b58b}
.nav-actions{display:flex;align-items:center;gap:10px;white-space:nowrap}.plan{background:var(--green);color:#fff;border-radius:999px;padding:11px 18px;font-size:12px;font-weight:600}.plan:hover{transform:translateY(-2px);box-shadow:0 8px 18px rgba(31,96,68,.2)}
.hero{padding:155px 0 70px;background:linear-gradient(180deg,#edf1e9,#faf9f5);position:relative;overflow:hidden}.hero:after{content:"SHARE";position:absolute;right:-35px;top:100px;font:600 190px/.7 "Playfair Display",serif;color:rgba(24,61,49,.045);letter-spacing:-.08em}
.hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1.15fr .85fr;gap:70px;align-items:end}.eyebrow{font-size:10px;letter-spacing:.25em;text-transform:uppercase;color:#7c8780}.hero h1{font:600 clamp(48px,7vw,88px)/.94 "Playfair Display",serif;letter-spacing:-.05em;margin:12px 0 20px}.hero p{max-width:650px;color:var(--muted);font-size:15px;line-height:2;margin:0}.hero-side{border-left:1px solid var(--line);padding-left:28px}.hero-side b{font:600 42px "Playfair Display",serif;color:var(--green)}.hero-side span{display:block;color:var(--muted);font-size:11px;margin-top:3px}.hero-side p{font-size:12px;line-height:1.8;margin-top:15px}
.choices{padding:70px 0 90px}.section-head{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:28px}.section-label{font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#7d8780}.section-head h2{font:600 clamp(34px,4.5vw,58px)/1 "Playfair Display",serif;letter-spacing:-.04em;margin:8px 0 0}.section-head p{max-width:420px;font-size:12px;line-height:1.8;color:var(--muted);margin:0}
.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.choice{position:relative;min-height:360px;padding:38px;border:1px solid var(--line);border-radius:26px;overflow:hidden;background:#fff;box-shadow:0 10px 28px rgba(24,49,35,.05);transition:transform .25s,box-shadow .25s}.choice:hover{transform:translateY(-6px);box-shadow:0 20px 42px rgba(24,49,35,.1)}.choice:after{content:"";position:absolute;width:220px;height:220px;right:-70px;bottom:-90px;border-radius:50%;background:rgba(115,181,139,.12)}.choice-place{background:linear-gradient(145deg,#fff,#eef5ef)}.choice-shop{background:linear-gradient(145deg,#fff,#f5f1e8)}.choice-icon{font-size:45px;position:relative;z-index:1}.choice-number{position:absolute;right:25px;top:24px;color:rgba(24,61,49,.15);font:600 52px "Playfair Display"}.choice h3{position:relative;z-index:1;font:600 36px/1.05 "Playfair Display",serif;margin:25px 0 10px}.choice p{position:relative;z-index:1;max-width:480px;color:var(--muted);font-size:13px;line-height:1.9;margin:0}.choice-btn{position:relative;z-index:2;display:inline-flex;align-items:center;gap:10px;margin-top:25px;padding:12px 20px;border-radius:999px;background:var(--green);color:#fff;font-size:12px;font-weight:600}.choice-btn:hover{transform:translateY(-2px);box-shadow:0 10px 22px rgba(31,96,68,.2)}
.tip{margin-top:25px;padding:18px 20px;border:1px dashed rgba(24,61,49,.2);border-radius:16px;color:var(--muted);font-size:11px;line-height:1.8;background:rgba(255,255,255,.55)}.tip b{color:var(--green)}
@media(max-width:900px){.links{display:none}.nav .container{gap:12px}.nav-actions{margin-left:auto}.hero-grid{grid-template-columns:1fr;gap:30px}.hero-side{border-left:0;border-top:1px solid var(--line);padding:20px 0 0}.choice-grid{grid-template-columns:1fr}}
@media(max-width:560px){.container{width:calc(100% - 30px)}.nav,.nav .container{height:68px}.logo{font-size:20px}.logo span{display:none}.plan{padding:9px 13px}.hero{padding-top:115px}.hero h1{font-size:48px}.choices{padding-top:50px}.section-head{display:block}.section-head p{margin-top:14px}.choice{min-height:330px;padding:28px}.choice h3{font-size:31px}}
</style></head><body>
<nav class="nav"><div class="container">
<a class="logo" href="home.php">เที่ยว ตาก<span>TAK EXPLORE</span></a>
<div class="links"><a href="home.php">หน้าแรก</a><a href="places.php">สถานที่เที่ยว</a><a href="shops.php">ร้านอาหาร &amp; คาเฟ่</a><a href="trip-planner.php">วางแผนทริป</a></div>
<div class="nav-actions"><?php include("profile-widget.php"); ?></div>
</div></nav>
<header class="hero"><div class="container hero-grid"><div><div class="eyebrow">Share Your Tak · Community</div><h1>อยากเพิ่มอะไร<br>ให้ตาก?</h1><p>ช่วยกันเติมข้อมูลดี ๆ ให้ TAK EXPLORE เลือกสิ่งที่คุณอยากเพิ่ม แล้วกรอกข้อมูลในหน้าถัดไปได้เลย</p></div><div class="hero-side"><b>01 → 02</b><span>เลือกประเภทข้อมูล</span><p>เพิ่มร้านหรือสถานที่ท่องเที่ยวที่คุณรู้จัก พร้อมรายละเอียดและตำแหน่งบนแผนที่ เพื่อให้คนอื่นค้นพบตากในมุมของคุณ</p></div></div></header>
<main class="choices"><div class="container"><div class="section-head"><div><div class="section-label">Choose what to share / 01</div><h2>คุณอยากเพิ่มอะไร?</h2></div><p>ข้อมูลที่คุณเพิ่มจะกลายเป็นส่วนหนึ่งของแหล่งข้อมูลใน TAK EXPLORE และคุณสามารถกลับมาแก้ไขข้อมูลของตัวเองได้ภายหลัง</p></div>
<div class="choice-grid">
<article class="choice choice-shop"><span class="choice-number">01</span><div class="choice-icon">🍜</div><h3>เพิ่มร้าน</h3><p>ร้านอาหาร คาเฟ่ ร้านค้า หรือร้านน่าสนใจที่อยากแนะนำให้คนอื่นได้รู้จัก พร้อมชื่อร้าน หมวดหมู่ รายละเอียด รูปภาพ และตำแหน่ง</p><a class="choice-btn" href="add-shop.php">เพิ่มร้านใหม่ <span>↗</span></a></article>
<article class="choice choice-place"><span class="choice-number">02</span><div class="choice-icon">🏞️</div><h3>เพิ่มสถานที่เที่ยว</h3><p>สถานที่ท่องเที่ยว จุดชมวิว น้ำตก ภูเขา หรือมุมพิเศษของตากที่ยังไม่มีในระบบ ช่วยให้คนอื่นวางแผนทริปได้ง่ายขึ้น</p><a class="choice-btn" href="add-place.php">เพิ่มสถานที่ใหม่ <span>↗</span></a></article>
</div>
<div class="tip"><b>TIP</b> · เพิ่มข้อมูลแล้วสามารถกลับไปที่โปรไฟล์เพื่อดูรายการของคุณ และแก้ไขเฉพาะข้อมูลที่คุณเป็นคนเพิ่มได้</div>
</div></main>
<?php include("global-search.php"); ?></body></html>