<?php
session_start();$open_connect=1;require('connect.php');
if(!isset($_SESSION['id_account'])){header('Location:form-login.php');exit;}
$id=(int)($_GET['id']??0);$uid=(int)$_SESSION['id_account'];
$q=mysqli_query($connect,"SELECT * FROM shop WHERE id_shop=$id AND id_account=$uid LIMIT 1");$shop=$q?mysqli_fetch_assoc($q):null;
if(!$shop){http_response_code(403);die('คุณไม่มีสิทธิ์แก้ไขร้านนี้');}
?><!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>แก้ไขร้าน | TAK EXPLORE</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Prompt:wght@300;400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="modern.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css"><style>
body{margin:0;background:#faf9f5;color:#18231e;font-family:Prompt,sans-serif}.wrap{width:min(1100px,calc(100% - 30px));margin:auto}.nav{height:76px;border-bottom:1px solid #ddd;background:#fff;display:flex;align-items:center}.logo{font:600 24px "Playfair Display";color:#183d31;text-decoration:none}.hero{padding:65px 0 35px;background:linear-gradient(#edf1e9,#faf9f5)}.ey{font-size:10px;letter-spacing:.25em;color:#7d8780}.hero h1{font:600 55px "Playfair Display";margin:10px 0}.hero p{color:#68736c}.form{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:25px 0 70px}.panel{background:#fff;border:1px solid #dfe3dd;border-radius:22px;padding:25px}.field{margin-bottom:15px}.field label{display:block;font-size:12px;color:#68736c;margin-bottom:6px}.field input,.field select,.field textarea{width:100%;box-sizing:border-box;padding:11px;border:1px solid #d8ded8;border-radius:11px;font:14px Prompt}.field textarea{min-height:100px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}#map{height:380px;border-radius:16px;overflow:hidden}.btn{width:100%;border:0;background:#183d31;color:white;padding:14px;border-radius:999px;font:600 14px Prompt}.current img{display:block;width:160px;height:100px;object-fit:cover;border-radius:12px;margin-top:8px}.image-upload-list{display:grid;gap:8px}.image-upload-row{display:flex;gap:8px;align-items:center}.image-upload-row input[type=file]{flex:1;min-width:0}.image-remove{width:42px;height:42px;border:1px solid #d8ded8;background:#fff;border-radius:11px;color:#9a4b4b;font-size:22px;cursor:pointer}.image-remove:disabled{opacity:.35;cursor:not-allowed}.image-add{margin-top:9px;border:1px dashed #9aada2;background:#f7faf6;color:#183d31;border-radius:11px;padding:10px 14px;font:500 13px Prompt;cursor:pointer}.existing-images{display:grid;gap:10px;margin-bottom:10px}.existing-image{display:flex;align-items:center;gap:10px;padding:8px;border:1px solid #dfe3dd;border-radius:12px;background:#fafbf9}.existing-image img{width:110px;height:75px;object-fit:cover;border-radius:9px}.existing-image label{margin:0!important;color:#9a4b4b!important;cursor:pointer}.existing-image input{width:auto!important}@media(max-width:800px){.form{grid-template-columns:1fr}.hero h1{font-size:43px}}
</style></head><body><nav class="nav"><div class="wrap"><a class="logo" href="shops.php">เที่ยว ตาก · TAK EXPLORE</a></div></nav><header class="hero"><div class="wrap"><div class="ey">MY CONTRIBUTION · EDIT SHOP</div><h1>แก้ไขร้านของฉัน</h1><p>แก้ไขได้เฉพาะร้านที่คุณเป็นคนเพิ่มเข้าระบบ</p></div></header><main class="wrap"><form class="form" method="POST" action="process-edit-shop.php" enctype="multipart/form-data"><input type="hidden" name="id_shop" value="<?=$id?>"><section class="panel"><h2>ข้อมูลร้าน</h2><div class="field"><label>ชื่อร้าน</label><input name="name_shop" value="<?=htmlspecialchars($shop['name_shop'])?>" required></div><div class="field"><label>หมวดหมู่</label><select name="category_shop" required><?php foreach(['ร้านอาหาร','คาเฟ่','ร้านค้า','อื่นๆ'] as $c):?><option value="<?=htmlspecialchars($c)?>" <?=$shop['category_shop']===$c?'selected':''?>><?=htmlspecialchars($c)?></option><?php endforeach;?></select></div><div class="field"><label>ที่อยู่ / จุดสังเกต</label><input name="address_shop" value="<?=htmlspecialchars($shop['address_shop']??'')?>"></div><div class="field"><label>รายละเอียด</label><textarea name="description_shop"><?=htmlspecialchars($shop['description_shop']??'')?></textarea></div><div class="field"><label>รูปร้าน (เพิ่ม/ลบได้หลายรูป)</label>
<?php $shop_images=array_values(array_filter(explode('|',(string)$shop['image_shop']))); ?>
<div class="existing-images"><?php foreach($shop_images as $img): ?><div class="existing-image"><img src="<?=htmlspecialchars($img)?>" alt=""><label><input type="checkbox" name="remove_images[]" value="<?=htmlspecialchars($img)?>"> ลบรูปนี้</label></div><?php endforeach; ?></div>
<div id="shop-image-list" class="image-upload-list"><div class="image-upload-row"><input type="file" name="image_shop[]" accept="image/jpeg,image/png"><button type="button" class="image-remove" disabled>×</button></div></div>
<button type="button" id="add-shop-image" class="image-add">＋ เพิ่มช่องรูป</button><small style="display:block;margin-top:8px;color:#68736c">เพิ่มรูปทีละช่อง และเลือกลบรูปเดิมได้</small></div></section><section class="panel"><h2>ตำแหน่งร้าน</h2><p style="font-size:11px;color:#68736c">คลิกแผนที่หรือเลื่อนหมุดเพื่อเปลี่ยนตำแหน่ง</p><div id="map"></div><div class="row"><div class="field"><label>ละติจูด</label><input id="lat" name="lat_shop" value="<?=htmlspecialchars($shop['lat_shop'])?>" readonly required></div><div class="field"><label>ลองจิจูด</label><input id="lng" name="lng_shop" value="<?=htmlspecialchars($shop['lng_shop'])?>" readonly required></div></div><button class="btn">บันทึกการแก้ไข</button></section></form></main><script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script><script>
const lat=parseFloat(document.getElementById('lat').value),lng=parseFloat(document.getElementById('lng').value);const map=L.map('map').setView([lat,lng],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);const marker=L.marker([lat,lng],{draggable:true}).addTo(map);function set(p){document.getElementById('lat').value=p.lat.toFixed(7);document.getElementById('lng').value=p.lng.toFixed(7);marker.setLatLng(p)}map.on('click',e=>set(e.latlng));marker.on('dragend',()=>set(marker.getLatLng()));
const shopImageList=document.getElementById('shop-image-list'),addShopImage=document.getElementById('add-shop-image');
function refreshShopRemove(){const rows=[...shopImageList.querySelectorAll('.image-upload-row')];rows.forEach(r=>r.querySelector('.image-remove').disabled=rows.length===1)}
addShopImage.addEventListener('click',()=>{const row=document.createElement('div');row.className='image-upload-row';row.innerHTML='<input type="file" name="image_shop[]" accept="image/jpeg,image/png"><button type="button" class="image-remove">×</button>';row.querySelector('.image-remove').addEventListener('click',()=>{row.remove();refreshShopRemove()});shopImageList.appendChild(row);refreshShopRemove()});refreshShopRemove();
</script></body></html>