<?php
session_start();
$open_connect=1; require('connect.php');

$place_images = [
 'thi-lo-su'=>'images/places/thi-lo-su.jpg','doi-musoe'=>'images/places/doi-musoe.jpg','bhumibol-dam'=>'images/places/bhumibol-dam.jpg',
 'mae-sot-market'=>'images/places/mae-sot-market.jpg','lan-sang'=>'images/places/lan-sang.jpg','taksin-maharat'=>'images/places/taksin-maharat.jpg',
 'wat-borommathat'=>'images/places/wat-borommathat.jpg','friendship-bridge'=>'images/places/friendship-bridge.jpg'
];
$place_gallery = [
 'thi-lo-su'=>['images/places/thi-lo-su.jpg','https://www.asiakingtravel.com/images/thumbs/2023/12/7437/image_400x400xcrop.webp'],
 'doi-hua-mot'=>['images/places/doi-hua-mot.jpg','images/places/gallery/doi-hua-mot-2.jpg'],
 'doi-thule'=>['images/places/doi-thule.jpg','https://s359.kapook.com/pagebuilder/ae823e95-80b2-4f9d-9d49-6aa3ac9d187c.jpg'],
 'mae-moei'=>['images/places/mae-moei.jpg','https://f.ptcdn.info/807/003/000/1365001557-IMG4973rs-o.jpg'],
 'pha-charoen'=>['images/places/pha-charoen.jpg','https://jinnyz.com/uploads/places/1675098882_%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%95%E0%B8%81%E0%B8%9E%E0%B8%B2%E0%B9%80%E0%B8%88%E0%B8%A3%E0%B8%B4%E0%B8%8D.jpg'],
 'thararak'=>['images/places/thararak.jpg','https://images.world-of-waterfalls.com/Thararak_010_01012009.jpg'],
 'wat-thai-wattanaram'=>['images/places/wat-thai-wattanaram.jpg','https://www.gettyimages.com/gi-resources/images/Creative/Creative_Assets/Images/Places/Thailand.jpg']
];
$places=[];
$q=mysqli_query($connect,"SELECT p.id_place,p.place_key,p.name_place,p.location_place,p.image_place,a.username_account,COALESCE(ROUND(AVG(r.rating),1),0) AS review_avg,COUNT(r.id_review) AS review_count FROM place p JOIN account a ON a.id_account=p.id_account LEFT JOIN reviews r ON r.item_type='place' AND r.id_place=p.id_place GROUP BY p.id_place,p.place_key,p.name_place,p.location_place,p.image_place,a.username_account ORDER BY p.id_place");
if($q){while($r=mysqli_fetch_assoc($q)){ $r['image_url']=$place_images[$r['place_key']]??($r['image_place']??''); $places[]=$r; }}
function review_badge($avg,$count){if($count>=10)return'ยอดนิยม';if($count>=3&&$avg>=4.3)return'แนะนำ';return'';}
$featured=array_slice($places,0,3); $others=array_slice($places,3);
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>สถานที่เที่ยว | TAK EXPLORE</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="modern.css"><link rel="stylesheet" href="gallery.css">
<style>
:root{--ink:#18231e;--muted:#68736c;--paper:#faf9f5;--cream:#f0eee5;--green:#183d31;--line:rgba(24,35,30,.13)}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Prompt,sans-serif}a{text-decoration:none;color:inherit}.container{width:min(1380px,calc(100% - 48px));margin:auto}
.nav{position:fixed;z-index:20;top:0;left:0;right:0;background:rgba(250,249,245,.9);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.nav .container{height:78px;display:flex;align-items:center;gap:28px}.logo{font:600 24px "Playfair Display";color:var(--green)}.logo span{font:500 10px Prompt;letter-spacing:.18em;color:var(--muted);margin-left:9px}.links{display:flex;gap:28px;margin:auto}.links a{font-size:13px;color:var(--muted);padding:28px 0;border-bottom:2px solid transparent}.links a.active,.links a:hover{color:var(--green);border-color:var(--green)}.plan{background:var(--green);color:#fff;border-radius:999px;padding:11px 18px;font-size:12px;font-weight:600}
.hero{padding:150px 0 65px;background:linear-gradient(180deg,#edf1e9,#faf9f5);position:relative;overflow:hidden}.hero:after{content:"TAK";position:absolute;right:-15px;top:65px;font:600 270px/.7 "Playfair Display";color:rgba(24,61,49,.055);letter-spacing:-.08em}.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:end;position:relative;z-index:1}.eyebrow,.label{font-size:10px;letter-spacing:.23em;text-transform:uppercase;color:#7d8780}.hero h1{font:600 clamp(50px,7vw,92px)/.92 "Playfair Display";letter-spacing:-.05em;margin:12px 0 20px}.hero p{max-width:620px;color:var(--muted);font-size:15px;line-height:2}.hero-side{border-left:1px solid var(--line);padding-left:28px}.hero-side b{font:600 42px "Playfair Display";color:var(--green)}.hero-side p{font-size:12px;line-height:1.8;color:var(--muted)}
.section{padding:75px 0}.head{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:28px}.head h2{font:600 clamp(34px,4.5vw,58px)/1 "Playfair Display";margin:8px 0 0;letter-spacing:-.04em}.head p{max-width:420px;font-size:12px;line-height:1.8;color:var(--muted)}
.grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:15px}.card{position:relative;min-height:450px;border-radius:24px;overflow:hidden;background:#244437;color:#fff}.card:nth-child(n+2){margin-top:45px;min-height:390px}.photo{position:absolute;inset:0;background:center/cover no-repeat;transition:.7s}.card:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,16,11,.9),transparent 62%)}.card:hover .photo{transform:scale(1.06)}.tag{position:absolute;z-index:2;top:16px;left:16px;background:rgba(250,249,245,.92);color:var(--green);padding:6px 11px;border-radius:999px;font-size:10px;font-weight:600}.body{position:absolute;z-index:2;left:24px;right:24px;bottom:22px}.body h3{font:600 30px/1.05 "Playfair Display";margin:0 0 8px}.body p{font-size:11px;line-height:1.7;color:rgba(255,255,255,.72);margin:0}.loc{display:block;font-size:10px;color:rgba(255,255,255,.65);margin-top:10px}.all{background:var(--cream);padding:75px 0}.all-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.small{background:#fff;border:1px solid var(--line);border-radius:20px;overflow:hidden;transition:.25s}.small:hover{transform:translateY(-5px);box-shadow:0 15px 35px rgba(20,40,30,.09)}.small-photo{aspect-ratio:1.2;background:center/cover no-repeat}.small-info{padding:16px}.small-info h3{font-size:15px;margin:0 0 5px}.small-info p{font-size:10px;color:var(--muted);margin:0;line-height:1.7}.by{font-size:9px!important;margin-top:10px!important}.cta{padding:85px 0;background:var(--green);color:#fff}.cta .container{display:flex;justify-content:space-between;align-items:center;gap:30px}.cta h2{font:600 clamp(38px,5vw,65px)/1 "Playfair Display";margin:8px 0}.cta p{color:rgba(255,255,255,.68);font-size:13px}.cta a{background:#f5f1e8;color:var(--green);padding:13px 21px;border-radius:999px;font-size:12px;font-weight:600;white-space:nowrap}
@media(max-width:900px){.links{display:none}.hero-grid{grid-template-columns:1fr;gap:30px}.hero-side{border-left:0;border-top:1px solid var(--line);padding:20px 0}.grid{grid-template-columns:1fr 1fr}.card:first-child{grid-column:1/-1}.card:nth-child(n+2){margin-top:0}.all-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.container{width:calc(100% - 30px)}.hero{padding-top:115px}.head{display:block}.head p{margin-top:14px}.grid,.all-grid{grid-template-columns:1fr}.card:first-child{grid-column:auto}.card,.card:nth-child(n+2){min-height:410px}.cta .container{display:block}.cta a{display:inline-block;margin-top:12px}}
</style></head><body data-logged-in="<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>" data-user-id="<?php echo isset($_SESSION['id_account'])?(int)$_SESSION['id_account']:0; ?>">
<nav class="nav"><div class="container"><a class="logo" href="home.php">เที่ยว ตาก<span>TAK EXPLORE</span></a><div class="links"><a href="home.php">หน้าแรก</a><a class="active" href="places.php">สถานที่เที่ยว</a><a href="shops.php">ร้านอาหาร & คาเฟ่</a><a href="trip-planner.php">วางแผนทริป</a></div><div style="display:flex;align-items:center;gap:10px"><?php include("profile-widget.php"); ?><a class="plan" href="contribute.php">+ เพิ่มข้อมูล</a></div></div></nav>
<header class="hero"><div class="container hero-grid"><div><div class="eyebrow">Discover Tak · Selected Places</div><h1>สถานที่เที่ยว<br>ที่อยากให้คุณไป</h1><p>รวมจุดหมายที่น่าสนใจของจังหวัดตาก ตั้งแต่ธรรมชาติ น้ำตก ภูเขา เขื่อน ไปจนถึงจุดเที่ยวในเมือง เลือกที่ชอบแล้วเพิ่มเข้าทริปของคุณได้ทันที</p></div><div class="hero-side"><b><?php echo count($places); ?>+</b><span>จุดหมายใน TAK EXPLORE</span><p>เริ่มจากสถานที่ยอดนิยม หรือเลื่อนลงเพื่อค้นพบมุมอื่น ๆ ของตาก</p></div></div></header>
<section class="section"><div class="container"><div class="head"><div><div class="label">Recommended / 01</div><h2>สถานที่ที่น่าสนใจ<br>แนะนำให้ลองไป</h2></div><p>สถานที่เด่นที่เราอยากให้คุณลองแวะระหว่างเดินทางในตาก</p></div><div class="grid">
<?php foreach($featured as $i=>$p): ?><article class="card" data-gallery='<?php echo htmlspecialchars(json_encode($place_gallery[$p['place_key']]??[$p['image_url']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8'); ?>' data-title='<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>' data-location='<?php echo htmlspecialchars($p['location_place'],ENT_QUOTES,'UTF-8'); ?>' data-description='จุดหมายที่น่าสนใจในจังหวัดตาก' data-review-type='place' data-review-id='<?php echo (int)$p['id_place']; ?>' data-review-avg='<?php echo (float)$p['review_avg']; ?>' data-review-count='<?php echo (int)$p['review_count']; ?>' data-review-logged-in='<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>' data-trip-id='<?php echo htmlspecialchars($p['place_key']); ?>' data-trip-title='<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>'><div class="photo" style="background-image:url('<?php echo htmlspecialchars($p['image_url']); ?>')"></div><span class="tag"><?php echo $i===0?'ยอดฮิต':($i===1?'ธรรมชาติ':($i===2?'เขื่อน':'ป่า & น้ำตก')); ?></span><button class="trip-add-btn" type="button" data-trip-id="<?php echo htmlspecialchars($p['place_key']); ?>" aria-label="เพิ่มเข้าทริป">＋ เพิ่มเข้าทริป</button><div class="body"><h3><?php echo htmlspecialchars($p['name_place']); ?></h3><?php if($p['review_count']>0): ?><div class="rating-line">★ <?php echo number_format((float)$p['review_avg'],1); ?> <span>(<?php echo (int)$p['review_count']; ?> รีวิว)</span></div><?php endif; ?><?php if($b=review_badge((float)$p['review_avg'],(int)$p['review_count'])): ?><span class="recommend-badge"><?php echo $b; ?></span><?php endif; ?><p>จุดหมายที่น่าสนใจสำหรับทริปตากของคุณ</p><span class="loc">● <?php echo htmlspecialchars($p['location_place']); ?></span></div></article><?php endforeach; ?>
</div></div></section>
<section class="all"><div class="container"><div class="head"><div><div class="label">Explore more / 02</div><h2>สถานที่อื่น ๆ ที่น่าค้นพบ</h2></div><p>เลื่อนดูสถานที่ทั้งหมดที่สมาชิกของเราแนะนำ</p></div><div class="all-grid">
<?php foreach($others as $p): ?><article class="small" data-gallery='<?php echo htmlspecialchars(json_encode($place_gallery[$p['place_key']]??[$p['image_url']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8'); ?>' data-title='<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>' data-location='<?php echo htmlspecialchars($p['location_place'],ENT_QUOTES,'UTF-8'); ?>' data-description='จุดหมายที่น่าสนใจในจังหวัดตาก' data-review-type='place' data-review-id='<?php echo (int)$p['id_place']; ?>' data-review-avg='<?php echo (float)$p['review_avg']; ?>' data-review-count='<?php echo (int)$p['review_count']; ?>' data-review-logged-in='<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>' data-trip-id='<?php echo htmlspecialchars($p['place_key']); ?>' data-trip-title='<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>'><div class="small-photo" style="background-image:url('<?php echo htmlspecialchars($p['image_url']); ?>')"></div><div class="small-info"><button class="trip-add-btn small-trip-add" type="button" data-trip-id="<?php echo htmlspecialchars($p['place_key']); ?>">＋ เพิ่มเข้าทริป</button><h3><?php echo htmlspecialchars($p['name_place']); ?></h3><?php if($p['review_count']>0): ?><div class="rating-line light">★ <?php echo number_format((float)$p['review_avg'],1); ?> <span>(<?php echo (int)$p['review_count']; ?> รีวิว)</span></div><?php endif; ?><?php if($b=review_badge((float)$p['review_avg'],(int)$p['review_count'])): ?><span class="recommend-badge inline"><?php echo $b; ?></span><?php endif; ?><p><?php echo htmlspecialchars($p['location_place']); ?></p><p class="by">แนะนำโดย <?php echo htmlspecialchars($p['username_account']); ?></p></div></article><?php endforeach; ?></div></div></section>
<section class="cta"><div class="container"><div><div class="label" style="color:rgba(255,255,255,.5)">Your trip / 03</div><h2>เจอสถานที่ที่ใช่แล้ว?</h2><p>เพิ่มสถานที่ที่สนใจ แล้วไปจัดลำดับการเดินทางต่อใน Trip Planner</p></div><a href="trip-planner.php">วางแผนทริปของฉัน ↗</a></div></section>
<footer><div class="container" style="display:flex;justify-content:space-between"><span>TAK EXPLORE · เที่ยวตากในแบบของคุณ</span><span>© <?php echo date('Y'); ?> TAK EXPLORE</span></div></footer>
<script src="gallery.js?v=20261006-review6"></script><script src="trip-widget.js?v=20261006-4"></script>
</body></html>