<?php
session_start();$open_connect=1;require('connect.php');
$q=trim($_GET['q']??'');$places=[];$shops=[];
if($q!==''){
 $like='%'.$q.'%';
 $st=mysqli_prepare($connect,"SELECT p.id_place,p.place_key,p.name_place,p.location_place,p.description_place,p.image_place FROM place p WHERE p.name_place LIKE ? OR p.location_place LIKE ? OR p.description_place LIKE ? OR p.place_key LIKE ? ORDER BY p.id_place LIMIT 50");
 if($st){mysqli_stmt_bind_param($st,'ssss',$like,$like,$like,$like);mysqli_stmt_execute($st);$rs=mysqli_stmt_get_result($st);while($r=mysqli_fetch_assoc($rs))$places[]=$r;mysqli_stmt_close($st);}
 $st=mysqli_prepare($connect,"SELECT id_shop,name_shop,category_shop,address_shop,description_shop,image_shop FROM shop WHERE status_shop=1 AND (name_shop LIKE ? OR category_shop LIKE ? OR address_shop LIKE ? OR description_shop LIKE ?) ORDER BY id_shop LIMIT 50");
 if($st){mysqli_stmt_bind_param($st,'ssss',$like,$like,$like,$like);mysqli_stmt_execute($st);$rs=mysqli_stmt_get_result($st);while($r=mysqli_fetch_assoc($rs))$shops[]=$r;mysqli_stmt_close($st);}
}
function gallery_json($value){$arr=array_values(array_filter(array_map('trim',explode('|',(string)$value))));return htmlspecialchars(json_encode($arr,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8');}
function first_image($value){$arr=array_values(array_filter(array_map('trim',explode('|',(string)$value))));return $arr[0]??'';}
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ค้นหา | TAK EXPLORE</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="gallery.css">
<style>
*{box-sizing:border-box}body{margin:0;background:#faf9f5;color:#18231e;font-family:Prompt,sans-serif}.container{width:min(1200px,calc(100% - 32px));margin:auto}.nav{height:78px;background:rgba(250,249,245,.96);border-bottom:1px solid #dde2dc;display:flex;align-items:center}.nav .container{display:flex;align-items:center;justify-content:space-between}.logo{font:600 24px 'Playfair Display';color:#183d31;text-decoration:none}.back{color:#68736c;text-decoration:none;font-size:13px}.hero{padding:55px 0 35px}.eyebrow{font-size:10px;letter-spacing:.2em;color:#7d8780;text-transform:uppercase}.hero h1{font:600 clamp(42px,6vw,70px)/1 'Playfair Display';margin:10px 0}.hero p{color:#68736c}.search{display:flex;gap:10px;max-width:900px}.search input{flex:1;border:1px solid #d6ddd7;border-radius:14px;padding:14px;font:400 14px Prompt}.search button{border:0;border-radius:14px;background:#183d31;color:#fff;padding:0 24px;font:600 13px Prompt}.section{padding:35px 0}.section h2{font:600 38px 'Playfair Display';margin:0 0 22px}.section h2 small{font:400 13px Prompt;color:#68736c}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{position:relative;background:#fff;border:1px solid #e0e4df;border-radius:20px;overflow:hidden;cursor:pointer;transition:.25s}.card:hover{transform:translateY(-4px);box-shadow:0 15px 35px rgba(20,40,30,.09)}.photo{height:220px;background:center/cover no-repeat}.info{padding:16px}.info h3{font:600 21px 'Playfair Display';margin:0 0 7px}.info p{font-size:11px;color:#68736c;margin:5px 0;line-height:1.7}.actions{display:flex;gap:8px;margin-top:13px;align-items:center}.trip-add-btn{border:0;border-radius:999px;background:#183d31;color:#fff;padding:9px 14px;font:600 11px Prompt;cursor:pointer}.trip-add-btn.is-added{background:#e8eee9;color:#183d31}.view-photo{border:1px solid #d8ded8;border-radius:999px;background:#fff;color:#183d31;padding:8px 13px;font:500 11px Prompt;cursor:pointer}.empty{padding:28px;background:#f0f3ed;border-radius:18px;color:#68736c}
@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}.search{flex-direction:column}.search button{height:44px}}
</style></head>
<body data-logged-in="<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>" data-user-id="<?php echo isset($_SESSION['id_account'])?(int)$_SESSION['id_account']:0; ?>">
<nav class="nav"><div class="container"><a class="logo" href="home.php">เที่ยว ตาก · TAK EXPLORE</a><a class="back" href="javascript:history.back()">← กลับหน้าก่อน</a></div></nav>
<main class="container"><section class="hero"><div class="eyebrow">Search Tak Explore</div><h1>ค้นหาสถานที่</h1><p>ค้นหาสถานที่เที่ยว ร้านอาหาร และคาเฟ่ที่คุณอยากไป</p><form class="search" method="get"><input name="q" value="<?php echo htmlspecialchars($q); ?>" placeholder="เช่น น้ำตกทีลอซู, แม่สอด, คาเฟ่..." autofocus><button>ค้นหา</button></form></section>
<?php if($q===''): ?><div class="empty">พิมพ์ชื่อสถานที่ ร้าน หรือคำค้นที่ต้องการได้เลย</div><?php else: ?>
<section class="section"><h2>สถานที่เที่ยว <small>(<?php echo count($places); ?> รายการ)</small></h2><?php if($places): ?><div class="grid">
<?php foreach($places as $p): $img=first_image($p['image_place']); ?>
<article class="card" data-gallery="<?php echo gallery_json($p['image_place']); ?>" data-title="<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>" data-location="<?php echo htmlspecialchars($p['location_place'],ENT_QUOTES,'UTF-8'); ?>" data-description="<?php echo htmlspecialchars($p['description_place']?:'จุดหมายที่น่าสนใจในจังหวัดตาก',ENT_QUOTES,'UTF-8'); ?>" data-review-type="place" data-review-id="<?php echo (int)$p['id_place']; ?>" data-review-avg="0" data-review-count="0" data-review-logged-in="<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>" data-trip-id="<?php echo htmlspecialchars($p['place_key'],ENT_QUOTES,'UTF-8'); ?>" data-trip-title="<?php echo htmlspecialchars($p['name_place'],ENT_QUOTES,'UTF-8'); ?>">
<div class="photo" style="background-image:url('<?php echo htmlspecialchars($img); ?>')"></div><div class="info"><h3><?php echo htmlspecialchars($p['name_place']); ?></h3><p>📍 <?php echo htmlspecialchars($p['location_place']); ?></p><div class="actions"><button class="trip-add-btn" type="button" data-trip-id="<?php echo htmlspecialchars($p['place_key'],ENT_QUOTES,'UTF-8'); ?>">＋ เพิ่มเข้าทริป</button><button class="view-photo" type="button">ดูรูปภาพ</button></div></div></article>
<?php endforeach; ?></div><?php else: ?><div class="empty">ไม่พบสถานที่เที่ยวที่ตรงกับ “<?php echo htmlspecialchars($q); ?>”</div><?php endif; ?></section>
<section class="section"><h2>ร้านอาหาร & คาเฟ่ <small>(<?php echo count($shops); ?> รายการ)</small></h2><?php if($shops): ?><div class="grid">
<?php foreach($shops as $s): $img=first_image($s['image_shop']); ?>
<article class="card" data-gallery="<?php echo gallery_json($s['image_shop']); ?>" data-title="<?php echo htmlspecialchars($s['name_shop'],ENT_QUOTES,'UTF-8'); ?>" data-location="<?php echo htmlspecialchars($s['address_shop']?:'จังหวัดตาก',ENT_QUOTES,'UTF-8'); ?>" data-description="<?php echo htmlspecialchars($s['description_shop']?:'ร้านอาหารและคาเฟ่ในจังหวัดตาก',ENT_QUOTES,'UTF-8'); ?>" data-review-type="shop" data-review-id="<?php echo (int)$s['id_shop']; ?>" data-review-avg="0" data-review-count="0" data-review-logged-in="<?php echo isset($_SESSION['id_account'])?'1':'0'; ?>" data-trip-id="shop-<?php echo (int)$s['id_shop']; ?>" data-trip-title="<?php echo htmlspecialchars($s['name_shop'],ENT_QUOTES,'UTF-8'); ?>">
<div class="photo" style="background-image:url('<?php echo htmlspecialchars($img?:'images/hero-tak.jpeg'); ?>')"></div><div class="info"><h3><?php echo htmlspecialchars($s['name_shop']); ?></h3><p>📍 <?php echo htmlspecialchars($s['address_shop']?:'จังหวัดตาก'); ?> · <?php echo htmlspecialchars($s['category_shop']); ?></p><div class="actions"><button class="trip-add-btn" type="button" data-trip-id="shop-<?php echo (int)$s['id_shop']; ?>">＋ เพิ่มเข้าทริป</button><button class="view-photo" type="button">ดูรูปภาพ</button></div></div></article>
<?php endforeach; ?></div><?php else: ?><div class="empty">ไม่พบร้านอาหารหรือคาเฟ่ที่ตรงกับ “<?php echo htmlspecialchars($q); ?>”</div><?php endif; ?></section>
<?php endif; ?></main>
<script src="gallery.js?v=20261007-search2"></script><script src="trip-widget.js?v=20261007-search2"></script>
<script>document.querySelectorAll('.view-photo').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.closest('[data-gallery]').dispatchEvent(new MouseEvent('click',{bubbles:true}))}));</script>
<?php include('global-search.php'); ?></body></html>