<?php
session_start();
$open_connect=1; require('connect.php');
$shops=[];
$q=mysqli_query($connect,"SELECT s.id_shop,s.name_shop,s.category_shop,s.description_shop,s.address_shop,s.image_shop,a.username_account,COALESCE(ROUND(AVG(r.rating),1),0) AS review_avg,COUNT(r.id_review) AS review_count FROM shop s JOIN account a ON a.id_account=s.id_account LEFT JOIN reviews r ON r.item_type='shop' AND r.id_shop=s.id_shop WHERE s.status_shop=1 GROUP BY s.id_shop,s.name_shop,s.category_shop,s.description_shop,s.address_shop,s.image_shop,a.username_account ORDER BY s.created_at DESC");
if($q){while($r=mysqli_fetch_assoc($q))$shops[]=$r;}
$shop_gallery = [
 'TARA kaffee&Patisserie'=>['https://ak-d.tripcdn.com/images/1mi6w224x92vx34j88179.jpg?proc=source%2Ftrip','https://p16-va.lemon8cdn.com/tos-alisg-v-a3e477-sg/okebqeEDRAWVu6gn7Vp7iiAEDfJXFDA3REANoI~tplv-tej9nj120t-origin.webp'],
 'TARA Kaffee & Patisserie'=>['https://ak-d.tripcdn.com/images/1mi6w224x92vx34j88179.jpg?proc=source%2Ftrip','https://p16-va.lemon8cdn.com/tos-alisg-v-a3e477-sg/okebqeEDRAWVu6gn7Vp7iiAEDfJXFDA3REANoI~tplv-tej9nj120t-origin.webp'],
 'Bite Me Bakery & Cafe'=>['https://img.wongnai.com/p/1920x0/2021/04/28/e2cf2e48dd6043bbab085f8c6dea1175.jpg','https://img.wongnai.com/p/1920x0/2016/12/16/af7927d897c249c99bd1b784f0feeb7b.jpg'],
 'Weasel Coffee Maesot'=>['https://maesotdata.com/uploads/images/202406/image_870x_66739c54a4053.jpg','https://maesotdata.com/uploads/images/202406/image_870x_66739c536ab63.jpg'],
 'Tieng Na Coffee and Bakery Farm'=>['https://www.thaimiceconnect.com/images/upload/business/1712/17712/1630193092.jpg','https://img.wongnai.com/p/1920x0/2024/07/23/5244cd6a97014e10a5c28164b11bd77f.jpg']
];
function review_badge($avg,$count){ if($count>=10) return 'ยอดนิยม'; if($count>=3 && $avg>=4.3) return 'แนะนำ'; return ''; }
$featured=array_slice($shops,0,3); $others=array_slice($shops,3);
?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ร้านอาหาร & คาเฟ่ | TAK EXPLORE</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Prompt:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="modern.css"><link rel="stylesheet" href="gallery.css"><style>
:root{--ink:#18231e;--muted:#68736c;--paper:#faf9f5;--cream:#f0eee5;--green:#183d31;--line:rgba(24,35,30,.13)}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Prompt,sans-serif}a{text-decoration:none;color:inherit}.container{width:min(1380px,calc(100% - 48px));margin:auto}
.nav{position:fixed;z-index:20;top:0;left:0;right:0;background:rgba(250,249,245,.9);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.nav .container{height:78px;display:flex;align-items:center;gap:28px}.logo{font:600 24px "Playfair Display";color:var(--green)}.logo span{font:500 10px Prompt;letter-spacing:.18em;color:var(--muted);margin-left:9px}.links{display:flex;gap:28px;margin:auto}.links a{font-size:13px;color:var(--muted);padding:28px 0;border-bottom:2px solid transparent}.links a.active,.links a:hover{color:var(--green);border-color:var(--green)}.plan{background:var(--green);color:#fff;border-radius:999px;padding:11px 18px;font-size:12px;font-weight:600}.add{border:1px solid var(--green);color:var(--green);border-radius:999px;padding:10px 16px;font-size:12px}
.hero{padding:150px 0 65px;background:linear-gradient(180deg,#edf1e9,#faf9f5);position:relative;overflow:hidden}.hero:after{content:"EAT";position:absolute;right:-15px;top:65px;font:600 250px/.7 "Playfair Display";color:rgba(24,61,49,.055)}.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:end;position:relative;z-index:1}.eyebrow,.label{font-size:10px;letter-spacing:.23em;text-transform:uppercase;color:#7d8780}.hero h1{font:600 clamp(50px,7vw,92px)/.92 "Playfair Display";letter-spacing:-.05em;margin:12px 0 20px}.hero p{max-width:620px;color:var(--muted);font-size:15px;line-height:2}.hero-side{border-left:1px solid var(--line);padding-left:28px}.hero-side b{font:600 42px "Playfair Display";color:var(--green)}.hero-side p{font-size:12px;line-height:1.8;color:var(--muted)}
.section{padding:75px 0}.head{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:28px}.head h2{font:600 clamp(34px,4.5vw,58px)/1 "Playfair Display";margin:8px 0 0;letter-spacing:-.04em}.head p{max-width:420px;font-size:12px;line-height:1.8;color:var(--muted)}
.grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:15px}.card{position:relative;min-height:450px;border-radius:24px;overflow:hidden;background:#244437;color:#fff}.card:nth-child(n+2){margin-top:45px;min-height:390px}.photo{position:absolute;inset:0;background:center/cover no-repeat;transition:.7s}.card:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,16,11,.9),transparent 62%)}.card:hover .photo{transform:scale(1.06)}.tag{position:absolute;z-index:2;top:16px;left:16px;background:rgba(250,249,245,.92);color:var(--green);padding:6px 11px;border-radius:999px;font-size:10px;font-weight:600}.body{position:absolute;z-index:2;left:24px;right:24px;bottom:22px}.body h3{font:600 30px/1.05 "Playfair Display";margin:0 0 8px}.body p{font-size:11px;line-height:1.7;color:rgba(255,255,255,.72);margin:0}.loc{display:block;font-size:10px;color:rgba(255,255,255,.65);margin-top:10px}.all{background:var(--cream);padding:75px 0}.all-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.small{background:#fff;border:1px solid var(--line);border-radius:20px;overflow:hidden;transition:.25s}.small:hover{transform:translateY(-5px);box-shadow:0 15px 35px rgba(20,40,30,.09)}.small-photo{aspect-ratio:1.2;background:center/cover no-repeat}.small-info{padding:16px}.small-info h3{font-size:15px;margin:0 0 5px}.small-info p{font-size:10px;color:var(--muted);margin:0;line-height:1.7}.by{font-size:9px!important;margin-top:10px!important}.cta{padding:85px 0;background:var(--green);color:#fff}.cta .container{display:flex;justify-content:space-between;align-items:center;gap:30px}.cta h2{font:600 clamp(38px,5vw,65px)/1 "Playfair Display";margin:8px 0}.cta p{color:rgba(255,255,255,.68);font-size:13px}.cta a{background:#f5f1e8;color:var(--green);padding:13px 21px;border-radius:999px;font-size:12px;font-weight:600;white-space:nowrap}footer{padding:28px 0;color:#7a847e;font-size:11px}.foot{display:flex;justify-content:space-between}
@media(max-width:900px){.links{display:none}.hero-grid{grid-template-columns:1fr;gap:30px}.hero-side{border-left:0;border-top:1px solid var(--line);padding:20px 0}.grid{grid-template-columns:1fr 1fr}.card:first-child{grid-column:1/-1}.card:nth-child(n+2){margin-top:0}.all-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.container{width:calc(100% - 30px)}.hero{padding-top:115px}.head{display:block}.head p{margin-top:14px}.grid,.all-grid{grid-template-columns:1fr}.card:first-child{grid-column:auto}.card,.card:nth-child(n+2){min-height:410px}.cta .container{display:block}.cta a{display:inline-block;margin-top:12px}}
</style></head><body>
<nav class="nav"><div class="container"><a class="logo" href="home.php">เที่ยว ตาก<span>TAK EXPLORE</span></a><div class="links"><a href="home.php">หน้าแรก</a><a href="places.php">สถานที่เที่ยว</a><a class="active" href="shops.php">ร้านอาหาร & คาเฟ่</a><a href="trip-planner.php">วางแผนทริป</a></div><div style="display:flex;align-items:center;gap:10px"><?php include("profile-widget.php"); ?><a class="plan" href="contribute.php">+ เพิ่มข้อมูล</a></div></div></nav>
<header class="hero"><div class="container hero-grid"><div><div class="eyebrow">Taste Tak · Food & Coffee</div><h1>ร้านอร่อย<br>ที่อยากให้คุณลอง</h1><p>รวมร้านอาหาร คาเฟ่ และร้านน่าสนใจในตากที่สมาชิกช่วยกันแนะนำ ค้นหาร้านที่ใช่ แล้วเก็บไว้เป็นส่วนหนึ่งของทริปคุณ</p></div><div class="hero-side"><b><?php echo count($shops); ?>+</b><span>ร้านใน TAK EXPLORE</span><p>มีร้านใหม่เพิ่มขึ้นเรื่อย ๆ จากคนที่อยากแชร์มุมโปรดของตากให้คนอื่นได้รู้จัก</p></div></div></header>
<section class="section"><div class="container"><div class="head"><div><div class="label">Recommended / 01</div><h2>ร้านที่น่าสนใจ<br>แนะนำให้ลอง</h2></div><p>ร้านเด่นที่เราอยากให้คุณลองแวะระหว่างเดินทางในตาก</p></div><div class="grid">
<?php foreach($featured as $i=>$s): ?><article class="card" data-gallery='<?php echo htmlspecialchars(json_encode(array_merge([$s['image_shop'] ?: 'images/hero-tak.jpeg'],$shop_gallery[$s['name_shop']] ?? []), JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE), ENT_QUOTES, 'UTF-8'); ?>' data-title='<?php echo htmlspecialchars($s['name_shop'], ENT_QUOTES, 'UTF-8'); ?>' data-location='<?php echo htmlspecialchars($s['address_shop'] ?: 'จังหวัดตาก', ENT_QUOTES, 'UTF-8'); ?>' data-description='<?php echo htmlspecialchars($s['description_shop'] ?: 'ร้านอาหารและคาเฟ่ที่น่าสนใจในจังหวัดตาก', ENT_QUOTES, 'UTF-8'); ?>' data-review-type='shop' data-review-id='<?php echo (int)$s['id_shop']; ?>' data-review-avg='<?php echo (float)$s['review_avg']; ?>' data-review-count='<?php echo (int)$s['review_count']; ?>' data-review-logged-in='<?php echo isset($_SESSION['id_account']) ? '1' : '0'; ?>' data-trip-id='shop:<?php echo (int)$s['id_shop']; ?>'><div class="photo" style="background-image:url('<?php echo htmlspecialchars($s['image_shop'] ?: 'images/hero-tak.jpeg'); ?>')"></div><span class="tag"><?php echo htmlspecialchars($s['category_shop']); ?></span><button class="trip-add-btn" type="button" data-trip-id="shop:<?php echo (int)$s['id_shop']; ?>" aria-label="เพิ่มเข้าทริป"></button><div class="body"><h3><?php echo htmlspecialchars($s['name_shop']); ?></h3><?php if($s['review_count']>0): ?><div class="rating-line">★ <?php echo number_format((float)$s['review_avg'],1); ?> <span>(<?php echo (int)$s['review_count']; ?> รีวิว)</span></div><?php endif; ?><?php if($review_badge=review_badge((float)$s['review_avg'],(int)$s['review_count'])): ?><span class="recommend-badge"><?php echo $review_badge; ?></span><?php endif; ?><p><?php echo htmlspecialchars($s['description_shop'] ?: 'ร้านน่าสนใจสำหรับทริปของคุณ'); ?></p><span class="loc">● <?php echo htmlspecialchars($s['address_shop'] ?: 'จังหวัดตาก'); ?></span></div></article><?php endforeach; ?>
</div></div></section>
<section class="all"><div class="container"><div class="head"><div><div class="label">Explore more / 02</div><h2>ร้านอื่น ๆ ที่น่าค้นพบ</h2></div><p>เลื่อนดูร้านทั้งหมดที่สมาชิกของเราแนะนำ</p></div><div class="all-grid">
<?php foreach($others as $s): ?><article class="small" data-gallery='<?php echo htmlspecialchars(json_encode(array_merge([$s['image_shop'] ?: 'images/hero-tak.jpeg'],$shop_gallery[$s['name_shop']] ?? []), JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE), ENT_QUOTES, 'UTF-8'); ?>' data-title='<?php echo htmlspecialchars($s['name_shop'], ENT_QUOTES, 'UTF-8'); ?>' data-location='<?php echo htmlspecialchars($s['address_shop'] ?: 'จังหวัดตาก', ENT_QUOTES, 'UTF-8'); ?>' data-description='<?php echo htmlspecialchars($s['description_shop'] ?: 'ร้านอาหาร คาเฟ่ และร้านน่าสนใจในตาก', ENT_QUOTES, 'UTF-8'); ?>' data-review-type='shop' data-review-id='<?php echo (int)$s['id_shop']; ?>' data-review-avg='<?php echo (float)$s['review_avg']; ?>' data-review-count='<?php echo (int)$s['review_count']; ?>' data-review-logged-in='<?php echo isset($_SESSION['id_account']) ? '1' : '0'; ?>' data-trip-id='shop:<?php echo (int)$s['id_shop']; ?>'><div class="small-photo" style="background-image:url('<?php echo htmlspecialchars($s['image_shop'] ?: 'images/hero-tak.jpeg'); ?>')"></div><div class="small-info"><button class="trip-add-btn small-trip-add" type="button" data-trip-id="shop:<?php echo (int)$s['id_shop']; ?>" aria-label="เพิ่มเข้าทริป"></button><h3><?php echo htmlspecialchars($s['name_shop']); ?></h3><?php if($s['review_count']>0): ?><div class="rating-line light">★ <?php echo number_format((float)$s['review_avg'],1); ?> <span>(<?php echo (int)$s['review_count']; ?> รีวิว)</span></div><?php endif; ?><?php if($review_badge=review_badge((float)$s['review_avg'],(int)$s['review_count'])): ?><span class="recommend-badge inline"><?php echo $review_badge; ?></span><?php endif; ?><p><?php echo htmlspecialchars($s['category_shop']); ?> · <?php echo htmlspecialchars($s['address_shop'] ?: 'ตาก'); ?></p><p class="by">แนะนำโดย <?php echo htmlspecialchars($s['username_account']); ?></p></div></article><?php endforeach; ?></div></div></section>
<section class="cta"><div class="container"><div><div class="label" style="color:rgba(255,255,255,.5)">Share your favorite / 03</div><h2>มีร้านเด็ดที่ยังไม่มี?</h2><p>ช่วยเพิ่มร้านหรือสถานที่ที่คุณรู้จัก ให้คนอื่นค้นพบตากในมุมของคุณ</p></div><a href="contribute.php">เพิ่มข้อมูลใหม่ ↗</a></div></section>
<footer><div class="container foot"><span>TAK EXPLORE · เที่ยวตากในแบบของคุณ</span><span>© <?php echo date('Y'); ?> TAK EXPLORE</span></div></footer>
<script src="gallery.js?v=20261006-review6"></script><script src="trip-widget.js?v=20261006-1"></script>
</body></html>