(function(){
'use strict';
const KEY='takTripPlaces';
const getTrip=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch(e){return[]}};
const setTrip=v=>localStorage.setItem(KEY,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const meta={};
document.querySelectorAll('[data-trip-id][data-title]').forEach(card=>{
 const id=card.dataset.tripId;
 meta[id]={title:card.dataset.title||card.querySelector('h3')?.textContent?.trim()||'รายการ',loc:card.dataset.location||card.querySelector('.location,.loc,.meta')?.textContent?.replace(/^●\s*/,'').trim()||''};
});
const style=document.createElement('style');
style.textContent='#tak-trip-widget{position:fixed;right:22px;bottom:22px;z-index:4000;width:min(360px,calc(100vw - 28px));background:#fff;border:1px solid rgba(24,61,49,.12);border-radius:22px;box-shadow:0 22px 60px rgba(15,35,24,.2);overflow:hidden;transform:translateX(125%);opacity:0;pointer-events:none;transition:.35s cubic-bezier(.22,1,.36,1)}#tak-trip-widget.is-open{transform:translateX(0);opacity:1;pointer-events:auto}#tak-trip-widget .tw-head{padding:16px 18px;background:#183d31;color:#fff;display:flex;align-items:center;justify-content:space-between}#tak-trip-widget .tw-head strong{font-size:15px}.tw-count{font-size:11px;opacity:.75}#tak-trip-widget .tw-list{max-height:280px;overflow:auto;padding:10px 12px;margin:0;list-style:none}#tak-trip-widget .tw-item{display:flex;align-items:center;gap:9px;padding:9px 7px;border-bottom:1px solid #edf0eb}#tak-trip-widget .tw-num{width:25px;height:25px;border-radius:50%;background:#e7f0e9;color:#183d31;display:grid;place-items:center;font-size:11px;font-weight:700;flex:none}#tak-trip-widget .tw-info{min-width:0;flex:1}.tw-name{font-size:12px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tw-loc{font-size:9px;color:#7b857d;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#tak-trip-widget .tw-remove{border:0;background:transparent;color:#9aa39c;cursor:pointer;font-size:18px;padding:3px 6px}.tw-remove:hover{color:#b0443d}#tak-trip-widget .tw-actions{padding:12px;background:#f6f8f3;display:flex;gap:8px}.tw-create{flex:1;border:0;border-radius:999px;background:#183d31;color:#fff;padding:11px 14px;font:600 12px Prompt,sans-serif;cursor:pointer}.tw-create:hover{background:#123326;transform:translateY(-1px)}.tw-clear{border:1px solid #dce2da;background:#fff;color:#68736c;border-radius:999px;padding:0 13px;font:500 11px Prompt,sans-serif;cursor:pointer}.tw-clear:hover{border-color:#b7c2b8;color:#183d31}.trip-add-btn{border:0!important;border-radius:999px!important;background:#f5f1e8!important;color:#183d31!important;padding:8px 13px!important;font:600 11px Prompt,sans-serif!important;cursor:pointer!important;z-index:5}.card>.trip-add-btn{position:absolute;top:16px;right:16px}.small-trip-add{margin:8px 0 0}.trip-add-btn.is-added{background:#183d31!important;color:#fff!important}.trip-add-btn.is-added::after{content:" ✓ อยู่ในทริป"}.trip-add-btn:not(.is-added)::after{content:" + เพิ่มเข้าทริป"}@media(max-width:600px){#tak-trip-widget{right:10px;bottom:10px;width:calc(100vw - 20px)}#tak-trip-widget .tw-list{max-height:230px}}';
document.head.appendChild(style);
const box=document.createElement('aside');box.id='tak-trip-widget';box.innerHTML='<div class="tw-head"><strong>ทริปของฉัน</strong><span class="tw-count"></span></div><ul class="tw-list"></ul><div class="tw-actions"><button class="tw-create">สร้างทริป →</button><button class="tw-clear">ล้างทั้งหมด</button></div>';document.body.appendChild(box);
const list=box.querySelector('.tw-list'),count=box.querySelector('.tw-count');
function refresh(){const trip=getTrip();count.textContent=trip.length+' รายการ';box.classList.toggle('is-open',trip.length>0);list.innerHTML=trip.map((id,i)=>{const m=meta[id]||{title:id,loc:''};return '<li class="tw-item"><span class="tw-num">'+(i+1)+'</span><div class="tw-info"><div class="tw-name">'+esc(m.title)+'</div><div class="tw-loc">'+esc(m.loc)+'</div></div><button class="tw-remove" data-id="'+esc(id)+'" title=ลบ>×</button></li>'}).join('');document.querySelectorAll('.trip-add-btn').forEach(btn=>btn.classList.toggle('is-added',trip.includes(btn.dataset.tripId)));}
function toggle(id){let t=getTrip();t=t.includes(id)?t.filter(x=>x!==id):[...t,id];setTrip(t);refresh();window.dispatchEvent(new CustomEvent('takTripChanged',{detail:{trip:t}}));}
document.addEventListener('click',e=>{const b=e.target.closest('.trip-add-btn');if(b){e.preventDefault();e.stopPropagation();toggle(b.dataset.tripId);return;}const rm=e.target.closest('.tw-remove');if(rm){toggle(rm.dataset.id);return;}if(e.target.closest('.tw-clear')){setTrip([]);refresh();return;}if(e.target.closest('.tw-create')){if(!getTrip().length){alert('กรุณาเพิ่มสถานที่หรือร้านเข้าทริปก่อน');return;}window.location.href='trip-planner.php?from=directory';}});
window.addEventListener('storage',refresh);window.addEventListener('takTripChanged',refresh);refresh();
})();